name: Peak Performance Systems
favicon: null
layout_spectrum: 0.9975
typography_spectrum: 0.98247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2d3033'
    - '#d3830d'
    - '#858689'
    - '#99532b'
  brandStrength: 0.03642957587726414
  lightness: 0.7347685266286135
  saturation: 0.8786959841381758
  rhythmicContrast: 0.6899716942571104
purpose: []
